config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/timer', to: 'timer#timer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController

  def timer

  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_footer.html.haml
.footer.navbar-fixed-bottom.row-fluid.navbar-default
  .navbar-inner.center
    -# %p
    &copy;
    = t('app.author')

app/views/application/_navbar_top.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      .navbar-brand
        = link_to root_path do
          = image_tag 'logos/photos-icon-64x64', alt: 'мини-проекты'
          = t('app.name')
      %button.navbar-toggle.collapsed{type: 'button',
      data: {toggle: 'collapse', target: '#navbar-main'}}
        %span.sr-only
          = t('app.nav.nav_switcher')
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    %ul.nav.navbar-nav.collapse.navbar-collapse.navbar-right#navbar-main
      %li
        = link_to t('projects.timer.name'), timer_path
      %li
        = link_to "project 2", "#"
      %li
        = link_to "project 3", "#"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0"}
    %meta{'http-equiv'=>"X-UA-Compatible", 'content'=>"IE=edge"}
    %title= t('app.name')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'logos/favicon.ico'
    = favicon_link_tag 'logos/photos-icon-32x32.png', sizes: '32x32'
    = favicon_link_tag 'logos/photos-icon-128x128.png', rel: 'apple-touch-icon'
  %body
    = render 'application/navbar_top'
    #wrapper
      = yield
    = render 'application/footer'

app/views/timer/timer.html.haml
.container.project-name.text-uppercase.font-weight-bold
  %p.text-center
    = t('projects.timer.name')

.container.project.project-timer.center
  .btn-group.btn-group-justified
    = link_to fa_icon(:play), "#",
    class: 'btn btn-success btn-col-4', id: 'timer-play',
    remote: true
    = link_to fa_icon(:pause), "#",
    class: 'btn btn-warning btn-col-4', id: 'timer-pause',
    remote: true
    = link_to fa_icon(:repeat), "#",
    class: 'btn btn-info btn-col-4', id: 'timer-repeat',
    remote: true
  #timer
    #hour
      0
    &nbsp;:
    #minute
      0
    &nbsp;:
    #second
      15

  .timer-customise
    .input-group.bootstrap-timepicker.timepicker.time
      = text_field_tag('custom time', '',
      class: 'form-control input-small',
      id: 'timepicker')
      %span.input-group-addon
        %span.glyphicon.glyphicon-time
    = link_to fa_icon(:check), '#',
    class: 'btn btn-primary',
    id: 'timer-set',
    remote: true

app/views/welcome/index.html.haml
.container.text-justify
  %h1
    Добро пожаловать!
  %p
    Данное приложение ориентированно на получение практических
    навыков верстки страниц при помощи Bootstrap, использовании
    некоторых неизвестных мне возможностей
    Ruby on Rails, а также затрагивается работа с внешним API.
  %p
    В приложении существуют несколько учебных проектов
    каждый из которых направлен на оттачивание определенной
    составляющей веб-программирования.
  %p
    Их список можно увидеть в меню навигации.